### ISSUE TITLE
Unable to upload

### ISSUE THREAD

**Issue by mudasir18** [peprodev/wc-upload-reciept#1]
The plugin is not allowing to upload the receipt, Getting this error when uploading  .png,jpg,pdf.

Unknown Server Error Occured! Try again.

**Comment by amirhp-com** [comment]
Hi, this is due to your server settings. 
We are not getting such error on any of our sites.
My friend, You are free to contact me in person with **support@pepro.dev** and i will help you debug the issue.

**Comment by amirhp-com** [comment]
Please check you have the **fileinfo extension** for PHP and the function: _mime_content_type_ could be called correctly.

**Comment by alejandroisrv** [comment]
i have this same problem

**Comment by amirhp-com** [comment]
Please check you have the fileinfo extension for PHP and the function: mime_content_type could be called correctly.
